version: '3'

services:
  wind-server:
    image: sakitamclone/wind-server:0.0.1
    build:
      context: ./
      args:
        NODE_ENV: development
    hostname: wind-server
    environment:
      - CORS_ORIGIN=****
    ports:
      - "8080:3333"

volumes:
  yarn:
